### ISSUE TITLE
Release 4.2 no longer includes mo files

### ISSUE THREAD

**Issue by wosc** [zopefoundation/zope.app.locales#17]
After #13 only [includes po/pot](https://github.com/zopefoundation/zope.app.locales/commit/deb4c8db3dee153ee3640bcf333ae2ba4fb12e5c#diff-4425ec4892a0640706a7612e3c26160478a52d1cb052428124b2e79769ef72d2R25-R26) in the release, causing the translations to not be available out-of-the-box anymore. Is this intentional? If yes, I'd appreciate a pointer on how consumers of this package are expected to use it now (compile to mo as part of our local application package release _somehow_?). Thanks!

**Comment by icemac** [comment]
See https://github.com/zopefoundation/zope.app.locales/pull/6#pullrequestreview-127830531 how to create the *.mo files on the fly.

I plan to add instructions to the README of the package and probably also get rid of the *.mo files in the repository. (They are compiled files like *.pyc ones which are also not in the repository.)

**Comment by wosc** [comment]
Thank you for pointing that out, I did indeed not know about the on-the-fly compile option in zope.i18n. I'm not sure I _like_ it very much, either (for example: if the application runs in a container, it incurs the compile overhead, however minor, on each startup, even though the result cannot change as long as the package does not release a new version), but that might be my own problem to solve...

**Comment by icemac** [comment]
Version https://pypi.org/project/zope.app.locales/4.3/ again contains `*.mo` files.
